In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import files
upload = files.upload()

Saving heartdisease.csv to heartdisease.csv

In [4]:
df = pd.read_csv('heartdisease.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,67,1,3,162,145,0,2,145,1,0.8,2,2,2,0
1,57,0,2,140,238,1,1,186,1,5.1,0,1,2,0
2,43,0,3,118,265,0,2,102,1,4.8,1,1,2,0
3,71,0,3,159,172,0,0,200,1,4.4,2,2,0,1
4,36,0,3,103,126,0,2,154,1,0.2,0,0,2,1

In [5]:
df.shape

(303, 14)

In [6]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [9]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,52.953795,0.547855,1.429043,147.155116,349.663366,0.478548,0.983498,137.059406,0.537954,3.101650,0.973597,1.485149,1.026403,0.481848
std,14.371992,0.498528,1.176796,31.409162,128.883561,0.500366,0.827742,39.335748,0.499382,1.802215,0.805175,1.150415,0.849208,0.500497
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,40.000000,0.000000,0.000000,119.000000,241.000000,0.000000,0.000000,102.500000,0.000000,1.500000,0.000000,0.000000,0.000000,0.000000
50%,53.000000,1.000000,1.000000,149.000000,347.000000,0.000000,1.000000,139.000000,1.000000,3.200000,1.000000,2.000000,1.000000,0.000000
75%,65.000000,1.000000,3.000000,174.000000,454.500000,1.000000,2.000000,170.500000,1.000000,4.700000,2.000000,3.000000,2.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,3.000000,2.000000,1.000000

In [10]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [11]:
!pip install pgmpy==1.0.0
import pgmpy
print(pgmpy.__version__)

Collecting pgmpy==1.0.0
  Downloading pgmpy-1.0.0-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.2.3)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.11.0+cpu)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (0.14.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (4.67.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.5.3)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.4.0)
Collecting pyro-ppl (from pgmpy==1.0.0)
  Downloading pyro_ppl-1.9.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2026.3)
Collecting pyro-api>=0.1.1 (from pyro-ppl->pgmpy==1.0.0)
  Downloading pyro_api-0.1.2-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.32.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (2025.3.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->pgmpy==1.0.0) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (26.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->pgmpy==1.0.0) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch->pgmpy==1.0.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch->pgmpy==1.0.0) (3.0.3)
Downloading pgmpy-1.0.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 35.8 MB/s eta 0:00:00
Downloading pyro_ppl-1.9.1-py3-none-any.whl (755 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 47.8 MB/s eta 0:00:00
Downloading pyro_api-0.1.2-py3-none-any.whl (11 kB)
Installing collected packages: pyro-api, pyro-ppl, pgmpy
Successfully installed pgmpy-1.0.0 pyro-api-0.1.2 pyro-ppl-1.9.1
1.0.0

In [13]:
import pgmpy
print(pgmpy.__version__)

1.0.0

In [16]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator

model = DiscreteBayesianNetwork([
    ('age', 'target'),
    ('sex', 'target'),
    ('cp', 'target'),
    ('chol', 'target'),
    ('thalach', 'target')
])

mle = MaximumLikelihoodEstimator(model, df)

cpds = mle.get_parameters()

model.add_cpds(*cpds)

print(model.get_cpds())

[<TabularCPD representing P(age:48) at 0x7e36bb996470>, <TabularCPD representing P(target:2 | age:48, chol:206, cp:4, sex:2, thalach:124) at 0x7e36bba4b850>, <TabularCPD representing P(sex:2) at 0x7e36bba4b950>, <TabularCPD representing P(cp:4) at 0x7e36bb9c5e50>, <TabularCPD representing P(chol:206) at 0x7e36bb9c6030>, <TabularCPD representing P(thalach:124) at 0x7e36bba0bbd0>]

In [17]:
print(model.get_cpds('age'))

+---------+------------+
| age(29) | 0.0264026  |
+---------+------------+
| age(30) | 0.0330033  |
+---------+------------+
| age(31) | 0.0264026  |
+---------+------------+
| age(32) | 0.0165017  |
+---------+------------+
| age(33) | 0.0132013  |
+---------+------------+
| age(34) | 0.019802   |
+---------+------------+
| age(35) | 0.0231023  |
+---------+------------+
| age(36) | 0.0264026  |
+---------+------------+
| age(37) | 0.0264026  |
+---------+------------+
| age(38) | 0.00330033 |
+---------+------------+
| age(39) | 0.0264026  |
+---------+------------+
| age(40) | 0.0132013  |
+---------+------------+
| age(41) | 0.00990099 |
+---------+------------+
| age(42) | 0.019802   |
+---------+------------+
| age(43) | 0.0264026  |
+---------+------------+
| age(44) | 0.019802   |
+---------+------------+
| age(45) | 0.0132013  |
+---------+------------+
| age(46) | 0.0132013  |
+---------+------------+
| age(47) | 0.0165017  |
+---------+------------+
| age(48) | 0.019802   |
+---------+------------+
| age(49) | 0.0132013  |
+---------+------------+
| age(50) | 0.0165017  |
+---------+------------+
| age(51) | 0.019802   |
+---------+------------+
| age(52) | 0.039604   |
+---------+------------+
| age(53) | 0.019802   |
+---------+------------+
| age(54) | 0.0264026  |
+---------+------------+
| age(55) | 0.0165017  |
+---------+------------+
| age(56) | 0.029703   |
+---------+------------+
| age(57) | 0.0165017  |
+---------+------------+
| age(58) | 0.0132013  |
+---------+------------+
| age(59) | 0.00660066 |
+---------+------------+
| age(60) | 0.0330033  |
+---------+------------+
| age(61) | 0.029703   |
+---------+------------+
| age(62) | 0.00990099 |
+---------+------------+
| age(63) | 0.029703   |
+---------+------------+
| age(64) | 0.019802   |
+---------+------------+
| age(65) | 0.0264026  |
+---------+------------+
| age(66) | 0.00990099 |
+---------+------------+
| age(67) | 0.0363036  |
+---------+------------+
| age(68) | 0.0231023  |
+---------+------------+
| age(69) | 0.019802   |
+---------+------------+
| age(70) | 0.0231023  |
+---------+------------+
| age(71) | 0.00660066 |
+---------+------------+
| age(72) | 0.0363036  |
+---------+------------+
| age(73) | 0.0165017  |
+---------+------------+
| age(75) | 0.0165017  |
+---------+------------+
| age(76) | 0.0231023  |
+---------+------------+
| age(77) | 0.029703   |
+---------+------------+

In [19]:
print(model.get_cpds('sex'))

+--------+----------+
| sex(0) | 0.452145 |
+--------+----------+
| sex(1) | 0.547855 |
+--------+----------+

In [22]:
print(model.nodes())

['age', 'target', 'sex', 'cp', 'chol', 'thalach']